### ISSUE TITLE
Items per minute / hour

### ISSUE THREAD

**Issue by dhardy** [doomeer/factorio#15]
Instead of entering all production rates per second, could it be possible to enter per minute? I'm not sure if the best way would be via a global option or appending a 'unit' like `5m`.

**Comment by doomeer** [comment]
I'm not sure it is necessary as you can simply replace, in your head, all "per second" by "per minute". For instance, if I ask for 1 Science Pack 2 per second, it tells me I need 5.5 Iron Plates per second. So to get 1 Science Pack 2 per minute, I need 5.5 Iron Plates per minute :)

**Comment by Grokzen** [comment]
@dhardy @doomeer I second OP:s suggestion for at least changing stuff to be per minute instead of seconds. The hour or custom configurable is not needed imo.

Almost everything in factorio is calculated per minute and not per second. For me the site is kinda useless if i still have to sit and recalculate everything all the time from */sec to */min

**Comment by doomeer** [comment]
That's easy to do as it's just a matter of display (numbers won't change) so I can do that ;)

**Comment by doomeer** [comment]
Actually I think a long time ago somebody wanted me to change from /min to /s. So I guess both cases are useful. I may try to implement a setting.

I realize now that my previous remark was wrong, it's not just about changing /s to /min in your head, because for the number of assembly machines it's not that simple; so there is indeed value in having the setting :)

**Comment by doomeer** [comment]
Done! Added a new "Time Unit" setting in the Advanced Settings panel.

**Comment by Grokzen** [comment]
Awesome, good enough for me :) :+1:
