### ISSUE TITLE
Many broken image links 

### ISSUE THREAD

**Issue by mmysinger** [doomeer/factorio#25]
Many broken icon images links from the wiki started to appear recently. From a quick diagnosis, it looks like the majority can be fixed by switching the default space replacement character from dash ('-') to underscore ('_') for icons.

**Comment by Grokzen** [comment]
I noticed this also

**Comment by pfrenssen** [comment]
It would be better to host them locally instead of including the images directly from the Factorio wiki. Otherwise this will break again every time something changes upstream.

**Comment by Bilka2** [comment]
I moved a lot of icons on the wiki around. You can find all things that I moved [here.](https://hastebin.com/aneyarufit.rb) Left side are the new URL's, right side are the old ones. I don't think we will do such a mass move in the future, so you don't need to worry about this happening again. I'd not switch images hosts since you basically have automatically updating icons by using the wiki as a host.

Also as a heads up: Generally all pages on the wiki have titles as "Upper lower lower" case. While users do get redirected to the right page automatically, it might be easier if you'd directly link to the right page. We also try to use the in-game translations for pages names. You can find a mapping of page (and now also mostly icon) names to the factorio code names [here.](https://github.com/demodude4u/Java-Factorio-Data-Wrapper/blob/master/FactorioDataWrapper/res/wiki-naming.json)

**Comment by NixonK** [comment]
@Bilka2 Heya, I'm almost done with a pull request to fix this. Can you please also update the following (they still have the old format and I assume they need to be changed to use underscores?):
Shotgun Shells
Piercing Shotgun Shells
Active Provider Chest
Passive Provider Chest
Storage Chest
Requester Chest

**Comment by Bilka2** [comment]
The 6 files you mentioned have been moved to their right locations according to the second link in my previous comment (in-game names).

**Comment by doomeer** [comment]
Thanks to all of you for this! I'm  glad that the wiki images now have regular names.
